### ISSUE TITLE
Update Header Image w/ logo

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/khs-minithon.github.io#30]
This is just a note for me to have the logo created and put in place of the current header image.

**Comment by JoseRoman** [comment]
@theseanconn how is this going?

**Comment by theseanconn** [comment]
In progress.

On Tue, Oct 27, 2015 at 10:55 AM, Jose Roman <notifications@github.com>
wrote:

> @theseanconn <https://github.com/theseanconn> how is this going?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/30#issuecomment-151529398>
> .
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

Event Page <http://fourdiamonds.donordrive.com/event/khs16>    Twitter
<http://twitter.com/khsminithon>  Instagram
<http://instagram.com/khsminithon>

**Comment by JoseRoman** [comment]
@theseanconn I'm good with Photoshop, if you need help.

**Comment by theseanconn** [comment]
Dont add this yet... this is just a possible background header image. We may not use the logo as the background header and if we dont it would be better to use an image related to childhood cancer. For now though keep what we have up.
![possible background header image](https://cloud.githubusercontent.com/assets/14626073/10775954/9cf131b2-7ce3-11e5-9f01-e7335e2f4832.jpg)

**Comment by Ernie3** [comment]
@theseanconn up to you but to be honest I have heard a lot of good comments on the current background. It is easy on the eyes/dim, great quality, and it actually seems relevant (sparkler = a spark of hope). Like I said up to your but IMHO the current background is nice looking.

**Comment by theseanconn** [comment]
Good point. Lets just keep this open and ill ask the other committee chairs about it later.

**Comment by Ernie3** [comment]
Emphasize the spark of hope! if people asked, I told them that they went "Ohhhh" and really seemed to like it

**Comment by theseanconn** [comment]
Alright, ill keep that in mind


On Tue, Oct 27, 2015 at 8:08 PM, Ernie Wilson <notifications@github.com>
wrote:

> Emphasize the spark of hope! if people asked, I told them that they went
> "Ohhhh" and really seemed to like it
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/website/issues/30#issuecomment-151680418>
> .
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

*Website <http://khsminithon.org>*
Event Page <http://fourdiamonds.donordrive.com/event/khs16>
Twitter  <http://twitter.com/khsminithon>
Instagram <http://instagram.com/khsminithon>

**Comment by Ernie3** [comment]
Any updates on the logo? This will be a great addition

**Comment by Ernie3** [comment]
Doesn't look like we will have this for Tuesday

**Comment by Ernie3** [comment]
We will be on the newsletter on the 24th, change of plans

**Comment by Ernie3** [comment]
@theseanconn I would really like to know the status of the logo please. No word in a while. What's up?

**Comment by Ernie3** [comment]
centered the menu bar for now

**Comment by JoseRoman** [comment]
Duplicate
