### ISSUE TITLE
Some Minor Changes

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/khs-minithon.github.io#50]
I will continue adding to this thread as stuff comes up.

As of right now,

Under the "How To Sign Up" could we add more steps  for the PDF dancer packet when it is finished.
What we have up currently is the online registration. The very last step in the online registration should be as follows (only when the PDF is completed tho): "Complete Online Registration"
Then the next step should read "Print and complete Dancer Packet (link to PDF?) and turn in $20 registration fee to Ms. Teixeira."

**Comment by theseanconn** [comment]
Include by the social media section, namely the twitter feed, include something along the lines of:
"Don't forget to mention us @KHSMiniTHON and use that hash-tag #KHSFTK" or something... sound good?

**Comment by Ernie3** [comment]
Is the PDF finished?

**Comment by Ernie3** [comment]
Just email me the PDF when finished, I will implement the download
