### ISSUE TITLE
Facebook

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/khs-minithon.github.io#51]
Is it possible to put in a FB feed like the twitter ones?
Im not sure if it should be a feed of the page or the event itself b/c i post most of the stuff on the event page.

**Comment by Ernie3** [comment]
I'll look into it. @JoseRoman might already know

**Comment by JoseRoman** [comment]
Yes, this is possible. Any particular place where you would like this widget? @theseanconn @Ernie3

**Comment by Ernie3** [comment]
Differ to @theseanconn I would imagine the bottom tho

**Comment by theseanconn** [comment]
Yes the bottom.

On Tuesday, November 24, 2015, Ernie Wilson <notifications@github.com>
wrote:

> Differ to @theseanconn <https://github.com/theseanconn> I would imagine
> the bottom tho
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/khs-minithon.github.io/issues/51#issuecomment-159487676>
> .
>


-- 
~Sean

**Comment by theseanconn** [comment]
Do you need a link or any codes or anything? 
Im not sure if I want the main page (http://www.facebook.com/khsminithon) or the specific event page (https://www.facebook.com/events/924971434223058/)

**Comment by JoseRoman** [comment]
I just need to one which one you decide on and then I will be able to put it in the website

**Comment by theseanconn** [comment]
https://www.facebook.com/events/924971434223058/

**Comment by Ernie3** [comment]
Looks good

**Comment by theseanconn** [comment]
I feel that there should be a link to the event page too... the one that people can click if they are interested and/or going. https://www.facebook.com/events/924971434223058/

**Comment by JoseRoman** [comment]
@theseanconn FB doesn't have support to embed events in websites.

**Comment by theseanconn** [comment]
Okay never mind then.
@JoseRoman
