### ISSUE TITLE
Dancer Packet

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/khs-minithon.github.io#54]
The packet is ready but will probably have minor updates made in the future.
It is currently a google doc. Should I publish it as a website so it will automatically update when we update it or should I do something else. We want people to be able to download and print it.

**Comment by Ernie3** [comment]
For now just send/share it for now, we can always worry about that a little later but at least something will be up

**Comment by theseanconn** [comment]
Im actually going to hold off until tomorrow because the doc itself isnt done... Ms. Teixeira has a hard copy that is finished and is working on updating the doc online.

**Comment by theseanconn** [comment]
https://docs.google.com/document/d/1O3SJ9m9lDg2DKxEBlBTyxpO3xCIYha8PHllycmBBXzQ/edit?usp=sharing

**Comment by theseanconn** [comment]
can this go up ASAP
If you need anything else from me please let me know.

**Comment by theseanconn** [comment]
Thanks for putting it up @Ernie3 just noticed that there is an extra blank page. page 5 is blank and i think is extra.... there should only be 7 pages total.

**Comment by theseanconn** [comment]
And i also updated the packet a little... should redownload as pdf...
