### ISSUE TITLE
Minor edit

### ISSUE THREAD

**Issue by theseanconn** [KHS-Minithon/khs-minithon.github.io#55]
Can we make the links here bigger (DonorDrive page & the pdf download link)? or maybe some sort of button. 
![screen shot 2015-12-04 at 11 12 03 am](https://cloud.githubusercontent.com/assets/14626073/11594419/f01b7a3a-9a77-11e5-926c-65ff7141cc4d.png)

**Comment by Ernie3** [comment]
Ok, I will look into it this weekend
