### ISSUE TITLE
Add logo to website

### ISSUE THREAD

**Issue by Ernie3** [KHS-Minithon/khs-minithon.github.io#57]
Under or around it or whatever put "Logo Design by junior Tyler Bowdoin"

**Comment by JoseRoman** [comment]
@Ernie3, @theseanconn: I see on FB that the logo in the shirts is different than the first one I saw, which one is going to be in the website? Can you post the one you want in here (PNG format) @theseanconn ?

**Comment by theseanconn** [comment]
The one I want is the one that you did. Dont worry about the shirt logo.

On Tue, Feb 9, 2016 at 11:10 PM, Jose Roman <notifications@github.com>
wrote:

> @Ernie3 <https://github.com/Ernie3>, @theseanconn
> <https://github.com/theseanconn>: I see on FB that the logo in the shirts
> is different than the first one I saw, which one is going to be in the
> website? Can you post the one you want in here (PNG format) @theseanconn
> <https://github.com/theseanconn> ?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/KHS-Minithon/khs-minithon.github.io/issues/57#issuecomment-182187473>
> .
>



-- 
*For The Fight. For The Cure. For The Kids,*

*Sean Connolly*
*Kennett High School Mini-THON Head*

*Website <http://khsminithon.org>*
Event Page <http://fourdiamonds.donordrive.com/event/khs16>
Twitter  <http://twitter.com/khsminithon>
Instagram <http://instagram.com/khsminithon>
Facebook <https://www.facebook.com/khsminithon>
